name: Sync EPG (3 back / 3 forward)

on:
  schedule:
    - cron: "0 */4 * * *"   # כל 4 שעות
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download EPG (gz, 3 back / 3 forward)
        run: |
          set -e
          UA="Mozilla/5.0"
          # ננסה שתי תבניות כתובת עד שיורד gz
          curl -L --fail -A "$UA" -o tvteam.xml.gz "http://epg.team/tvteam.3.3.xml.gz" \
          || curl -L --fail -A "$UA" -o tvteam.xml.gz "http://epg.team/tvteam.xml.3.3.gz"
          test -s tvteam.xml.gz

      - name: Commit & push
        run: |
          set -e
          git config user.name "epg-bot"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "update epg gz (3/3)" || echo "no changes"
          git pull --rebase origin main || true
          git push origin HEAD:main
