name: Sync EPG (3 back / 3 forward)

on:
  schedule:
    - cron: "0 */4 * * *"   # כל 4 שעות
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download & compress EPG (3/3)
        run: |
          set -e
          UA="Mozilla/5.0"
          # הורדה כ-XML (שתי וריאציות כתובת), ואז דחיסה ל-GZ
          curl -L --fail -A "$UA" -o tvteam.xml "http://epg.team/tvteam.xml.3.3" \
          || curl -L --fail -A "$UA" -o tvteam.xml "http://epg.team/tvteam.3.3.xml"
          gzip -9 -c tvteam.xml > tvteam.xml.gz
          rm -f tvteam.xml

      - name: Commit & push
        run: |
          set -e
          git config user.name "epg-bot"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add tvteam.xml.gz
          git commit -m "update epg gz (3/3)" || echo "no changes"
          git push origin HEAD:main
