name: Sync EPG (3 back / 3 forward)

on:
  schedule:
    - cron: "0 */4 * * *"   # כל 4 שעות
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download EPG
        run: |
          curl -L --fail -A "Mozilla/5.0" -o tvteam.xml "http://epg.team/tvteam.xml.3.3"
      - name: Commit & push if changed
        run: |
          git config user.name "epg-bot"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain tvteam.xml)" ]; then
            git add tvteam.xml
            git commit -m "update epg"
            git push
          fi
