name: Sync EPG (3 back / 3 forward)

on:
  schedule:
    - cron: "0 */4 * * *"   # כל 4 שעות
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download EPG (3/3, compressed)
        run: |
          set -e
          UA="Mozilla/5.0"
          # ננסה שתי צורות כתובת עד שזה יורד
          curl -L --fail -A "$UA" -o tvteam.xml.gz "http://epg.team/tvteam.3.3.xml.gz" \
          || curl -L --fail -A "$UA" -o tvteam.xml.gz "http://epg.team/tvteam.xml.3.3.gz"

      - name: Commit & push if changed
        run: |
          git config user.name "epg-bot"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain tvteam.xml.gz)" ]; then
            git add tvteam.xml.gz
            git commit -m "update epg gz (3/3)"
            git push
          fi
